### ISSUE TITLE
常用问题整理：NTFS只读问题

### ISSUE THREAD

**Issue by hanzn-zzx** [pzm9012/doc-vite#4]
https://bbs.deepin.org/post/259187
解决方案：关闭Windows快速启动 https://bbs.deepin.org/post/258177
可否收录？文档里我没找到
@pzm9012

**Comment by pzm9012** [comment]
这个问题是被频繁提问的问题，直接整理到deepin 高频问题中。 已提交，见 https://github.com/pzm9012/doc-vite/commit/cd38d2304157d17745066cbad70ff89bb102c005 。
