### ISSUE TITLE
资源整理：翻阅2022-07至08的帖子

### ISSUE THREAD

**Issue by pzm9012** [pzm9012/doc-vite#8]

**Comment by hanzn-zzx** [comment]
要不还是咱俩一起看吧。你一个人看也不是事。

**Comment by pzm9012** [comment]
> 要不还是咱俩一起看吧。你一个人看也不是事。

你帮忙把近期的帖子添加一下，再同步发布一下就可以了。

**Comment by hanzn-zzx** [comment]
> 你帮忙把近期的帖子添加一下，再同步发布一下就可以了。
好的

**Comment by pzm9012** [comment]
从 https://bbs.deepin.org/post/239766 至 https://bbs.deepin.org/post/242333 为此期间的帖子。

**Comment by pzm9012** [comment]
从 https://bbs.deepin.org/post/239766 至 https://bbs.deepin.org/post/241040 为7月间的帖子，https://bbs.deepin.org/post/241041 至 https://bbs.deepin.org/post/242333 为8月间的帖子。
@hanzn-zzx 负责7月帖子， @pzm9012 负责8月帖子。

**Comment by pzm9012** [comment]
抱歉点错了 😿
